import type { ConversationStarter, Scrut, User } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1', display_name: 'Amina Kalu', avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&crop=face',
    country: 'Nigeria', city: 'Lagos',
    bio: 'Writer, observer of small things. Interested in how people make meaning out of ordinary days.',
    twitter: 'aminakalu', website: 'aminakalu.com',
    tip_link: 'https://buymeacoffee.com/aminakalu',
  },
  {
    id: 'u2', display_name: 'Daniel Rocha', avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=80&h=80&fit=crop&crop=face',
    country: 'Brazil', city: 'São Paulo',
    bio: 'Product designer. Thinking about cities, systems, and the distance between intention and outcome.',
    instagram: 'danielrocha.design',
    tip_link: 'https://paypal.me/danielrocha',
  },
  {
    id: 'u3', display_name: 'Sarah Mitchell', avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face',
    country: 'UK', city: 'Manchester',
    bio: 'Teacher. Asking questions for a living — might as well ask them here too.',
    twitter: 'sarahmitch',
    tip_link: 'https://ko-fi.com/sarahmitch',
  },
  {
    id: 'u4', display_name: 'Joel Tetteh', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    country: 'Ghana', city: 'Accra',
    bio: 'Musician and sound engineer. Most of what I want to say I say through a microphone.',
    instagram: 'joeltetteh_music', website: 'joeltetteh.com',
    tip_link: 'https://buymeacoffee.com/joeltetteh',
  },
  {
    id: 'u5', display_name: 'Yuki Hayashi', avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=80&h=80&fit=crop&crop=face',
    country: 'Japan', city: 'Tokyo',
    bio: 'Researcher studying how digital spaces change the way we form identity. Quietly curious.',
    tip_link: 'https://ko-fi.com/yukihayashi',
  },
  {
    id: 'u6', display_name: 'Marco Vitale', avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    country: 'Italy', city: 'Milan',
    bio: 'Architect and occasional philosopher. The built environment is a form of argument.',
    website: 'vitale.studio',
  },
  {
    id: 'u7', display_name: 'Priya Sharma', avatar_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&crop=face',
    country: 'India', city: 'Mumbai',
    bio: 'Documentary filmmaker. I point a camera at things people usually look away from.',
    instagram: 'priyasharma.films', twitter: 'priyasfilms',
  },
  {
    id: 'u8', display_name: 'Carlos Estrada', avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&crop=face',
    country: 'Mexico', city: 'Mexico City',
    bio: 'Journalist. Covering the gap between what governments say and what actually happens.',
    twitter: 'cestrada_mx',
  },
  {
    id: 'u9', display_name: 'Fatima Amrani', avatar_url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=80&h=80&fit=crop&crop=face',
    country: 'Morocco', city: 'Casablanca',
    bio: 'Studying law. Interested in what rules we invent, and which ones we quietly choose to ignore.',
  },
  {
    id: 'u10', display_name: 'Lena Weber', avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face',
    country: 'Germany', city: 'Berlin',
    bio: 'Therapist and reader. People are more interesting than they give themselves credit for.',
    website: 'lenaweber.de',
  },
  {
    id: 'u11', display_name: 'James Owusu', avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=80&h=80&fit=crop&crop=face',
    country: 'USA', city: 'Atlanta',
    bio: 'Software engineer by day, poet by night. Both involve debugging.',
    twitter: 'jowusu_writes', instagram: 'jameswrites',
  },
  {
    id: 'u12', display_name: 'Mei Lin', avatar_url: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=80&h=80&fit=crop&crop=face',
    country: 'China', city: 'Shanghai',
    bio: 'Food scientist and home cook. Flavor is a language and I\'m still learning vocabulary.',
    instagram: 'meilin.eats',
  },
];

export const MOCK_CONVERSATIONS: ConversationStarter[] = [
  {
    id: 'c1',
    user_id: 'platform',
    user: { id: 'platform', display_name: 'Scruttin', avatar_url: '', country: '' },
    type: 'question',
    body: "What's something you stopped caring about as you got older?",
    topic: 'Life',
    created_at: '2026-08-25T08:00:00Z',
    scrut_count: 2847,
    country_count: 41,
    is_platform: true,
    circulation_score: 0.92,
  },
  {
    id: 'c2',
    user_id: 'u3',
    user: MOCK_USERS[2],
    type: 'statement',
    body: 'Social media has made friendships shallower.',
    topic: 'Relationships',
    created_at: '2026-08-25T06:30:00Z',
    scrut_count: 1203,
    country_count: 28,
    is_platform: false,
    circulation_score: 0.78,
  },
  {
    id: 'c3',
    user_id: 'platform',
    user: { id: 'platform', display_name: 'Scruttin', avatar_url: '', country: '' },
    type: 'question',
    body: "What's something your parents were right about?",
    topic: 'Family',
    created_at: '2026-08-25T04:00:00Z',
    scrut_count: 3421,
    country_count: 47,
    is_platform: true,
    circulation_score: 0.95,
  },
  {
    id: 'c4',
    user_id: 'u1',
    user: MOCK_USERS[0],
    type: 'question',
    body: "What's something that's normal in your country but surprises foreigners?",
    topic: 'Culture',
    created_at: '2026-08-24T22:00:00Z',
    scrut_count: 892,
    country_count: 53,
    is_platform: false,
    circulation_score: 0.87,
  },
  {
    id: 'c5',
    user_id: 'platform',
    user: { id: 'platform', display_name: 'Scruttin', avatar_url: '', country: '' },
    type: 'question',
    body: 'When did you realise you were actually becoming an adult?',
    topic: 'Life',
    created_at: '2026-08-24T18:00:00Z',
    scrut_count: 1587,
    country_count: 33,
    is_platform: true,
    circulation_score: 0.85,
  },
  {
    id: 'c6',
    user_id: 'u5',
    user: MOCK_USERS[4],
    type: 'statement',
    body: 'Working from home makes people less social.',
    topic: 'Work',
    created_at: '2026-08-24T14:00:00Z',
    scrut_count: 741,
    country_count: 22,
    is_platform: false,
    circulation_score: 0.69,
  },
  {
    id: 'c7',
    user_id: 'platform',
    user: { id: 'platform', display_name: 'Scruttin', avatar_url: '', country: '' },
    type: 'question',
    body: "What's something adulthood didn't prepare you for?",
    topic: 'Life',
    created_at: '2026-08-24T10:00:00Z',
    scrut_count: 4102,
    country_count: 58,
    is_platform: true,
    circulation_score: 0.98,
  },
  {
    id: 'c8',
    user_id: 'u8',
    user: MOCK_USERS[7],
    type: 'question',
    body: 'What does success mean to you?',
    topic: 'Life',
    created_at: '2026-08-24T08:00:00Z',
    scrut_count: 2103,
    country_count: 39,
    is_platform: false,
    circulation_score: 0.81,
  },
];

export const MOCK_SCRUTS: Record<string, Scrut[]> = {
  c1: [
    { id: 's1', user: MOCK_USERS[0], conversation_id: 'c1', type: 'text', text: "Probably what strangers think of me. I used to edit everything — what I wore, what I said — based on imaginary opinions of people I'd never see again. Now? I genuinely don't track it. It's one of the nicest things about getting older.", created_at: '2026-08-25T09:00:00Z' },
    { id: 's2', user: MOCK_USERS[3], conversation_id: 'c1', type: 'voice', audio_duration: 43, created_at: '2026-08-25T09:05:00Z' },
    { id: 's3', user: MOCK_USERS[9], conversation_id: 'c1', type: 'text', text: "Being the smartest person in the room. I worked so hard to be seen as intelligent. At some point I realized that the most interesting thing I can do is be genuinely curious. Asking questions turned out to be more useful than performing answers.", created_at: '2026-08-25T09:10:00Z' },
    { id: 's4', user: MOCK_USERS[5], conversation_id: 'c1', type: 'voice_text', audio_duration: 31, text: "My reputation at school. None of it matters. The grade, the rank — irrelevant.", created_at: '2026-08-25T09:15:00Z' },
    { id: 's5', user: MOCK_USERS[10], conversation_id: 'c1', type: 'voice', audio_duration: 57, created_at: '2026-08-25T09:20:00Z' },
    { id: 's6', user: MOCK_USERS[6], conversation_id: 'c1', type: 'text', text: "Drama. In my twenties I was surrounded by it and even created some. Now I just quietly leave situations that feel like that. No explanation needed.", created_at: '2026-08-25T09:25:00Z' },
  ],
  c2: [
    { id: 's7', user: MOCK_USERS[1], conversation_id: 'c2', type: 'text', text: "I don't think social media makes friendships shallow. I think it reveals which friendships were already shallow. The platform just removes the friction that kept weak connections polite.", position: 'disagree', created_at: '2026-08-25T07:00:00Z' },
    { id: 's8', user: MOCK_USERS[4], conversation_id: 'c2', type: 'voice', audio_duration: 48, position: 'agree', created_at: '2026-08-25T07:10:00Z' },
    { id: 's9', user: MOCK_USERS[7], conversation_id: 'c2', type: 'text', text: "Unsure, honestly. I have friends I've never met in person who know me more deeply than people I grew up with. But I also see people performing friendship publicly while the actual relationship has evaporated. Both things are true.", position: 'unsure', created_at: '2026-08-25T07:20:00Z' },
    { id: 's10', user: MOCK_USERS[11], conversation_id: 'c2', type: 'voice', audio_duration: 52, position: 'agree', created_at: '2026-08-25T07:30:00Z' },
  ],
  c3: [
    { id: 's11', user: MOCK_USERS[2], conversation_id: 'c3', type: 'voice', audio_duration: 38, created_at: '2026-08-25T05:00:00Z' },
    { id: 's12', user: MOCK_USERS[8], conversation_id: 'c3', type: 'text', text: "That money problems don't go away when you earn more. They just change shape. My mum said this constantly and I thought she was being dramatic. She was not being dramatic.", created_at: '2026-08-25T05:10:00Z' },
    { id: 's13', user: MOCK_USERS[1], conversation_id: 'c3', type: 'voice_text', audio_duration: 44, text: "Sleep. They always said sleep early and I thought adults were boring. Turns out they were protecting something precious.", created_at: '2026-08-25T05:20:00Z' },
    { id: 's14', user: MOCK_USERS[6], conversation_id: 'c3', type: 'voice', audio_duration: 29, created_at: '2026-08-25T05:30:00Z' },
    { id: 's15', user: MOCK_USERS[10], conversation_id: 'c3', type: 'text', text: "Not everyone deserves an explanation. My dad used to say you don't owe anyone a reason for your decisions. I spent fifteen years arguing with that. He was completely right.", created_at: '2026-08-25T05:40:00Z' },
  ],
  c7: [
    { id: 's16', user: MOCK_USERS[3], conversation_id: 'c7', type: 'voice', audio_duration: 51, created_at: '2026-08-24T11:00:00Z' },
    { id: 's17', user: MOCK_USERS[9], conversation_id: 'c7', type: 'text', text: "How to manage money. I left school knowing how to calculate the area of shapes I've never needed to calculate in real life, but had no idea what a tax return was, how interest worked, or what a pension meant.", created_at: '2026-08-24T11:10:00Z' },
    { id: 's18', user: MOCK_USERS[4], conversation_id: 'c7', type: 'voice', audio_duration: 33, created_at: '2026-08-24T11:20:00Z' },
    { id: 's19', user: MOCK_USERS[0], conversation_id: 'c7', type: 'voice_text', audio_duration: 46, text: "That rest is productive. I kept thinking being exhausted meant I was working hard. It just meant I was bad at resting.", created_at: '2026-08-24T11:30:00Z' },
  ],
};

export const OPEN_SCRUTS: Scrut[] = [
  { id: 'o1', user: MOCK_USERS[2], conversation_id: null, type: 'text', text: "I've been thinking about how strange it is that we spend most of our lives doing things we didn't consciously choose. School, career path, city. Most of it was just... the default.", created_at: '2026-08-25T08:30:00Z' },
  { id: 'o2', user: MOCK_USERS[5], conversation_id: null, type: 'voice', audio_duration: 37, created_at: '2026-08-25T08:00:00Z' },
  { id: 'o3', user: MOCK_USERS[11], conversation_id: null, type: 'text', text: "Something happened today that reminded me you can know someone for years and still not know what they actually believe. Sobering.", created_at: '2026-08-25T07:40:00Z' },
  { id: 'o4', user: MOCK_USERS[7], conversation_id: null, type: 'voice', audio_duration: 29, created_at: '2026-08-25T07:00:00Z' },
  { id: 'o5', user: MOCK_USERS[3], conversation_id: null, type: 'text', text: "Here's something I don't understand: why do we treat rest like it's something you have to earn? You don't earn breathing.", created_at: '2026-08-25T06:30:00Z' },
];
